[build]
  command = "hugo --gc --minify"
  publish = "public"

[dev]
  command = "hugo server --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION        = "0.108.0"
  HUGO_ENABLEGITINFO  = "true"
