name: Lighthouse CI
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["$default-branch"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://pablogonzalez.me
            https://pablogonzalez.me/about/
            https://pablogonzalez.me/posts/
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage